%% ========================================================================
% BARRIDO DEL DESFASE DEL CONTROL RESONANTE
%
% M1:
%   utiliza velocidad observada
%   se barre phi_M1
%
% M2:
%   utiliza velocidad real
%   phi_M2 = 0 deg
%
% ========================================================================

clear;
clc;


%% ========================================================================
% CONFIGURACIÓN
% ========================================================================

model = ...
    'Simulacion_stepper';


% -------------------------------------------------------------------------
% Inicializar proyecto y parámetros
% -------------------------------------------------------------------------

InitFcn();


% -------------------------------------------------------------------------
% Velocidad de operación
% -------------------------------------------------------------------------

Wm_operacion = ...
    w_ref(end);


% -------------------------------------------------------------------------
% Ventana de análisis
% -------------------------------------------------------------------------

timeWindow = ...
    [0.12 0.20];


%% ========================================================================
% VALORES DE FASE A EVALUAR EN M1
% ========================================================================

% Ejemplo inicial:
%
% phi_values = -60:5:-50;
%
% Barrido amplio:
%
% phi_values = -180:10:180;
%
% Barrido fino:
%
% phi_values = -70:1:-40;

phi_values = ...
    linspace(-50,-60,3);


N = ...
    numel(phi_values);


% -------------------------------------------------------------------------
% M2 permanece siempre sin compensación adicional
% -------------------------------------------------------------------------

phi_M2_fixed = ...
    0;


%% ========================================================================
% INFORMACIÓN DEL BARRIDO
% ========================================================================

fprintf('\n');

fprintf('=============================================================\n');
fprintf(' BARRIDO DE FASE - M1 SENSORLESS\n');
fprintf('=============================================================\n');


fprintf( ...
    'Simulaciones      : %d\n', ...
    N);


fprintf( ...
    'Phi M1 desde      : %+8.2f deg\n', ...
    phi_values(1));


fprintf( ...
    'Phi M1 hasta      : %+8.2f deg\n', ...
    phi_values(end));


if N > 1

    fprintf( ...
        'Paso             : %+8.2f deg\n', ...
        phi_values(2)-phi_values(1));

end


fprintf( ...
    'Phi M2 fijo       : %+8.2f deg\n', ...
    phi_M2_fixed);


fprintf( ...
    'Wm operación      : %8.4f rad/s\n', ...
    Wm_operacion);


fprintf( ...
    'Ventana análisis  : %.4f - %.4f s\n', ...
    timeWindow(1), ...
    timeWindow(2));


fprintf('=============================================================\n\n');


%% ========================================================================
% PREPARAR SIMULACIONES
% ========================================================================

simIn(1:N) = ...
    Simulink.SimulationInput(model);


for k = 1:N


    %% ====================================================================
    % PARÁMETROS M1
    %
    % M1 utiliza velocidad observada.
    %
    % Se modifica solamente su fase.
    % =====================================================================

    RI_M1_k = ...
        RI_params_M1;


    RI_M1_k.phi = ...
        phi_values(k)*pi/180;


    %% ====================================================================
    % PARÁMETROS M2
    %
    % M2 utiliza velocidad real.
    %
    % Se mantiene sin compensación adicional de fase.
    % =====================================================================

    RI_M2_k = ...
        RI_params_M2;


    RI_M2_k.phi = ...
        phi_M2_fixed*pi/180;


    %% ====================================================================
    % CREAR SimulationInput
    % =====================================================================

    simIn(k) = ...
        Simulink.SimulationInput(model);


    %% --------------------------------------------------------------------
    % Estructura resonante M1
    % ---------------------------------------------------------------------

    simIn(k) = ...
        simIn(k).setVariable( ...
            'RI_params_M1', ...
            RI_M1_k);


    %% --------------------------------------------------------------------
    % Estructura resonante M2
    % ---------------------------------------------------------------------

    simIn(k) = ...
        simIn(k).setVariable( ...
            'RI_params_M2', ...
            RI_M2_k);


    %% --------------------------------------------------------------------
    % Guardar también las fases en grados
    %
    % Útil para InitFcn, diagnóstico y registro.
    % ---------------------------------------------------------------------

    simIn(k) = ...
        simIn(k).setVariable( ...
            'phi_M1_deg', ...
            phi_values(k));


    simIn(k) = ...
        simIn(k).setVariable( ...
            'phi_M2_deg', ...
            phi_M2_fixed);


    %% --------------------------------------------------------------------
    % Modo barrido
    % ---------------------------------------------------------------------

    simIn(k) = ...
        simIn(k).setVariable( ...
            'modo_barrido', ...
            true);


end


%% ========================================================================
% EJECUTAR SIMULACIONES
%
% IMPORTANTE:
%
% RI_params_M1 y RI_params_M2 son utilizados como parámetros no tunables.
%
% Por esto:
%
%       UseFastRestart = off
%
% ========================================================================

simOut = ...
    sim( ...
        simIn, ...
        'UseFastRestart','off', ...
        'ShowProgress','on');


fprintf('\n');
fprintf('Barrido finalizado.\n');


%% ========================================================================
% ANALIZAR SIMULACIONES
% ========================================================================

for k = 1:N


    r = ...
        FinishFcn( ...
            simOut(k), ...
            Wm_operacion, ...
            timeWindow, ...
            false);


    if k == 1

        resultado = ...
            r;

    else

        resultado(k) = ...
            r;

    end


end


%% ========================================================================
% EXTRAER VARIABLES M1
% ========================================================================

M1_phi_Wm = ...
    arrayfun( ...
        @(r) r.M1.phi_Wm, ...
        resultado).';


M1_gain_Wm = ...
    arrayfun( ...
        @(r) r.M1.gain_Wm, ...
        resultado).';


M1_phi_Iq = ...
    arrayfun( ...
        @(r) r.M1.phi_Iq, ...
        resultado).';


M1_gain_Iq = ...
    arrayfun( ...
        @(r) r.M1.gain_Iq, ...
        resultado).';


M1_phi_theta = ...
    arrayfun( ...
        @(r) r.M1.phi_theta, ...
        resultado).';


M1_gain_theta = ...
    arrayfun( ...
        @(r) r.M1.gain_theta, ...
        resultado).';


M1_phi_TPR = ...
    arrayfun( ...
        @(r) r.M1.phi_TPR, ...
        resultado).';


M1_gain_TPR = ...
    arrayfun( ...
        @(r) r.M1.gain_TPR, ...
        resultado).';


M1_Wm_mean = ...
    arrayfun( ...
        @(r) r.M1.Wm_mean, ...
        resultado).';


M1_Wm_std = ...
    arrayfun( ...
        @(r) r.M1.Wm_std, ...
        resultado).';


M1_Wm_ripple = ...
    arrayfun( ...
        @(r) r.M1.Wm_ripple_pp, ...
        resultado).';


M1_Wm_RMSE = ...
    arrayfun( ...
        @(r) r.M1.Wm_RMSE, ...
        resultado).';


%% ========================================================================
% EXTRAER VARIABLES M2
% ========================================================================

M2_phi_Wm = ...
    arrayfun( ...
        @(r) r.M2.phi_Wm, ...
        resultado).';


M2_gain_Wm = ...
    arrayfun( ...
        @(r) r.M2.gain_Wm, ...
        resultado).';


M2_phi_Iq = ...
    arrayfun( ...
        @(r) r.M2.phi_Iq, ...
        resultado).';


M2_gain_Iq = ...
    arrayfun( ...
        @(r) r.M2.gain_Iq, ...
        resultado).';


M2_phi_theta = ...
    arrayfun( ...
        @(r) r.M2.phi_theta, ...
        resultado).';


M2_gain_theta = ...
    arrayfun( ...
        @(r) r.M2.gain_theta, ...
        resultado).';


M2_phi_TPR = ...
    arrayfun( ...
        @(r) r.M2.phi_TPR, ...
        resultado).';


M2_gain_TPR = ...
    arrayfun( ...
        @(r) r.M2.gain_TPR, ...
        resultado).';


M2_Wm_mean = ...
    arrayfun( ...
        @(r) r.M2.Wm_mean, ...
        resultado).';


M2_Wm_std = ...
    arrayfun( ...
        @(r) r.M2.Wm_std, ...
        resultado).';


M2_Wm_ripple = ...
    arrayfun( ...
        @(r) r.M2.Wm_ripple_pp, ...
        resultado).';


M2_Wm_RMSE = ...
    arrayfun( ...
        @(r) r.M2.Wm_RMSE, ...
        resultado).';


%% ========================================================================
% TABLA FINAL
% ========================================================================

Resultados = table( ...
    ...
    phi_values(:), ...
    ...
    M1_phi_Wm, ...
    M2_phi_Wm, ...
    ...
    M1_gain_Wm, ...
    M2_gain_Wm, ...
    ...
    M1_phi_Iq, ...
    M2_phi_Iq, ...
    ...
    M1_gain_Iq, ...
    M2_gain_Iq, ...
    ...
    M1_phi_theta, ...
    M2_phi_theta, ...
    ...
    M1_gain_theta, ...
    M2_gain_theta, ...
    ...
    M1_phi_TPR, ...
    M2_phi_TPR, ...
    ...
    M1_gain_TPR, ...
    M2_gain_TPR, ...
    ...
    M1_Wm_mean, ...
    M2_Wm_mean, ...
    ...
    M1_Wm_std, ...
    M2_Wm_std, ...
    ...
    M1_Wm_ripple, ...
    M2_Wm_ripple, ...
    ...
    M1_Wm_RMSE, ...
    M2_Wm_RMSE, ...
    ...
    'VariableNames',{ ...
        ...
        'Phi_M1_deg', ...
        ...
        'Fase_Wm_M1_deg', ...
        'Fase_Wm_M2_deg', ...
        ...
        'Gain_Wm_M1', ...
        'Gain_Wm_M2', ...
        ...
        'Fase_Iq_M1_deg', ...
        'Fase_Iq_M2_deg', ...
        ...
        'Gain_Iq_M1', ...
        'Gain_Iq_M2', ...
        ...
        'Fase_theta_M1_deg', ...
        'Fase_theta_M2_deg', ...
        ...
        'Gain_theta_M1', ...
        'Gain_theta_M2', ...
        ...
        'Fase_TPR_M1_deg', ...
        'Fase_TPR_M2_deg', ...
        ...
        'Gain_TPR_M1', ...
        'Gain_TPR_M2', ...
        ...
        'Wm_media_M1', ...
        'Wm_media_M2', ...
        ...
        'Std_Wm_M1', ...
        'Std_Wm_M2', ...
        ...
        'Ripple_PP_Wm_M1', ...
        'Ripple_PP_Wm_M2', ...
        ...
        'RMSE_Wm_M1', ...
        'RMSE_Wm_M2'});


disp(Resultados);


%% ========================================================================
% MEJOR RESULTADO M1
%
% El objetivo del barrido es optimizar M1.
%
% M2 solamente sirve como referencia.
% ========================================================================

[bestRipple_M1,idx_best] = ...
    min( ...
        Resultados.Ripple_PP_Wm_M1);


fprintf('\n');

fprintf('=============================================================\n');
fprintf(' MEJOR RESULTADO M1 - SENSORLESS\n');
fprintf('=============================================================\n');


fprintf( ...
    'Phi M1 aplicado      = %+8.2f deg\n', ...
    Resultados.Phi_M1_deg(idx_best));


fprintf( ...
    'Fase TPR/Tdtm M1     = %+8.2f deg\n', ...
    Resultados.Fase_TPR_M1_deg(idx_best));


fprintf( ...
    'Gain TPR/Tdtm M1     = %8.4f\n', ...
    Resultados.Gain_TPR_M1(idx_best));


fprintf( ...
    'Fase Wm obs/real M1  = %+8.2f deg\n', ...
    Resultados.Fase_Wm_M1_deg(idx_best));


fprintf( ...
    'Gain Wm obs/real M1  = %8.4f\n', ...
    Resultados.Gain_Wm_M1(idx_best));


fprintf( ...
    'Ripple Wm M1 p-p     = %.6f rad/s\n', ...
    bestRipple_M1);


fprintf( ...
    'Std Wm M1            = %.6f rad/s\n', ...
    Resultados.Std_Wm_M1(idx_best));


fprintf( ...
    'RMSE Wm M1           = %.6f rad/s\n', ...
    Resultados.RMSE_Wm_M1(idx_best));


fprintf('-------------------------------------------------------------\n');


fprintf( ...
    'M2 referencia:\n');


fprintf( ...
    'Phi M2               = %+8.2f deg\n', ...
    phi_M2_fixed);


fprintf( ...
    'Fase TPR/Tdtm M2     = %+8.2f deg\n', ...
    Resultados.Fase_TPR_M2_deg(idx_best));


fprintf( ...
    'Ripple Wm M2 p-p     = %.6f rad/s\n', ...
    Resultados.Ripple_PP_Wm_M2(idx_best));


fprintf( ...
    'RMSE Wm M2           = %.6f rad/s\n', ...
    Resultados.RMSE_Wm_M2(idx_best));


fprintf('=============================================================\n');


%% ========================================================================
% COMPROBAR QUE M2 PERMANECE CONSTANTE
% ========================================================================

variacion_M2 = ...
    max(Resultados.Ripple_PP_Wm_M2) - ...
    min(Resultados.Ripple_PP_Wm_M2);


fprintf('\n');

fprintf('=============================================================\n');
fprintf(' COMPROBACIÓN M2\n');
fprintf('=============================================================\n');


fprintf( ...
    'Variación ripple M2 = %.8f rad/s\n', ...
    variacion_M2);


if variacion_M2 < 1e-6

    fprintf( ...
        'M2 permanece constante durante el barrido.\n');

else

    fprintf( ...
        'ADVERTENCIA: M2 cambia durante el barrido de M1.\n');

end


fprintf('=============================================================\n');


%% ========================================================================
% DESENROLLAR FASE TPR PARA GRÁFICOS
% ========================================================================

Fase_TPR_M1_unwrap = ...
    rad2deg( ...
        unwrap( ...
            deg2rad( ...
                Resultados.Fase_TPR_M1_deg)));


Fase_TPR_M2_unwrap = ...
    rad2deg( ...
        unwrap( ...
            deg2rad( ...
                Resultados.Fase_TPR_M2_deg)));


%% ========================================================================
% GRÁFICO 1
% RIPPLE DE VELOCIDAD
% ========================================================================

figure;


plot( ...
    Resultados.Phi_M1_deg, ...
    Resultados.Ripple_PP_Wm_M1, ...
    '-o', ...
    'LineWidth',1.5);


hold on;


plot( ...
    Resultados.Phi_M1_deg, ...
    Resultados.Ripple_PP_Wm_M2, ...
    '-o', ...
    'LineWidth',1.5);


grid on;


xlabel( ...
    '\phi_{M1} aplicado [deg]');


ylabel( ...
    'Ripple W_m p-p [rad/s]');


legend( ...
    'M1 - Wm observada', ...
    'M2 - Wm real', ...
    'Location','best');


title( ...
    'Ripple de velocidad vs fase de compensación M1');


hold off;


%% ========================================================================
% GRÁFICO 2
% FASE TPR / TDTM
% ========================================================================

figure;


plot( ...
    Resultados.Phi_M1_deg, ...
    Fase_TPR_M1_unwrap, ...
    '-o', ...
    'LineWidth',1.5);


hold on;


plot( ...
    Resultados.Phi_M1_deg, ...
    Fase_TPR_M2_unwrap, ...
    '-o', ...
    'LineWidth',1.5);


grid on;


xlabel( ...
    '\phi_{M1} aplicado [deg]');


ylabel( ...
    '\angle(T_{PR}/T_{dtm}) [deg]');


legend( ...
    'M1 - Wm observada', ...
    'M2 - Wm real', ...
    'Location','best');


title( ...
    'Fase efectiva del torque resonante');


hold off;


%% ========================================================================
% GRÁFICO 3
% FASE Wm OBSERVADA / REAL
% ========================================================================

figure;


plot( ...
    Resultados.Phi_M1_deg, ...
    Resultados.Fase_Wm_M1_deg, ...
    '-o', ...
    'LineWidth',1.5);


hold on;


plot( ...
    Resultados.Phi_M1_deg, ...
    Resultados.Fase_Wm_M2_deg, ...
    '-o', ...
    'LineWidth',1.5);


grid on;


xlabel( ...
    '\phi_{M1} aplicado [deg]');


ylabel( ...
    '\angle(W_{m,obs}/W_{m,real}) [deg]');


legend( ...
    'M1', ...
    'M2', ...
    'Location','best');


title( ...
    'Desfase de velocidad observada');


hold off;


%% ========================================================================
% GRÁFICO 4
% RMSE DE VELOCIDAD
% ========================================================================

figure;


plot( ...
    Resultados.Phi_M1_deg, ...
    Resultados.RMSE_Wm_M1, ...
    '-o', ...
    'LineWidth',1.5);


hold on;


plot( ...
    Resultados.Phi_M1_deg, ...
    Resultados.RMSE_Wm_M2, ...
    '-o', ...
    'LineWidth',1.5);


grid on;


xlabel( ...
    '\phi_{M1} aplicado [deg]');


ylabel( ...
    'RMSE W_m [rad/s]');


legend( ...
    'M1 - Wm observada', ...
    'M2 - Wm real', ...
    'Location','best');


title( ...
    'RMSE de velocidad vs fase de compensación');


hold off;