/*
 * File: ekf_6steps.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Fri Nov 14 13:01:21 2025
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                ekf_6steps

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     10

/* Input Port  0 */
#define IN_PORT_0_NAME                 Va
#define INPUT_0_DIMS_ND                {1,1}
#define INPUT_0_NUM_ELEMS              1
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 Vb
#define INPUT_1_DIMS_ND                {1,1}
#define INPUT_1_NUM_ELEMS              1
#define INPUT_1_WIDTH                  1
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  real_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define INPUT_1_UNIT                   ""
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      1-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  0
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            9
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 R
#define INPUT_2_DIMS_ND                {1,1}
#define INPUT_2_NUM_ELEMS              1
#define INPUT_2_WIDTH                  1
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  real_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define INPUT_2_UNIT                   ""
#define IN_2_BUS_BASED                 0
#define IN_2_BUS_NAME
#define IN_2_DIMS                      1-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  0
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            9
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125

/* Input Port  3 */
#define IN_PORT_3_NAME                 L
#define INPUT_3_DIMS_ND                {1,1}
#define INPUT_3_NUM_ELEMS              1
#define INPUT_3_WIDTH                  1
#define INPUT_DIMS_3_COL               1
#define INPUT_3_DTYPE                  real_T
#define INPUT_3_COMPLEX                COMPLEX_NO
#define INPUT_3_UNIT                   ""
#define IN_3_BUS_BASED                 0
#define IN_3_BUS_NAME
#define IN_3_DIMS                      1-D
#define INPUT_3_FEEDTHROUGH            1
#define IN_3_ISSIGNED                  0
#define IN_3_WORDLENGTH                8
#define IN_3_FIXPOINTSCALING           1
#define IN_3_FRACTIONLENGTH            9
#define IN_3_BIAS                      0
#define IN_3_SLOPE                     0.125

/* Input Port  4 */
#define IN_PORT_4_NAME                 Kt
#define INPUT_4_DIMS_ND                {1,1}
#define INPUT_4_NUM_ELEMS              1
#define INPUT_4_WIDTH                  1
#define INPUT_DIMS_4_COL               1
#define INPUT_4_DTYPE                  real_T
#define INPUT_4_COMPLEX                COMPLEX_NO
#define INPUT_4_UNIT                   ""
#define IN_4_BUS_BASED                 0
#define IN_4_BUS_NAME
#define IN_4_DIMS                      1-D
#define INPUT_4_FEEDTHROUGH            1
#define IN_4_ISSIGNED                  0
#define IN_4_WORDLENGTH                8
#define IN_4_FIXPOINTSCALING           1
#define IN_4_FRACTIONLENGTH            9
#define IN_4_BIAS                      0
#define IN_4_SLOPE                     0.125

/* Input Port  5 */
#define IN_PORT_5_NAME                 J
#define INPUT_5_DIMS_ND                {1,1}
#define INPUT_5_NUM_ELEMS              1
#define INPUT_5_WIDTH                  1
#define INPUT_DIMS_5_COL               1
#define INPUT_5_DTYPE                  real_T
#define INPUT_5_COMPLEX                COMPLEX_NO
#define INPUT_5_UNIT                   ""
#define IN_5_BUS_BASED                 0
#define IN_5_BUS_NAME
#define IN_5_DIMS                      1-D
#define INPUT_5_FEEDTHROUGH            1
#define IN_5_ISSIGNED                  0
#define IN_5_WORDLENGTH                8
#define IN_5_FIXPOINTSCALING           1
#define IN_5_FRACTIONLENGTH            9
#define IN_5_BIAS                      0
#define IN_5_SLOPE                     0.125

/* Input Port  6 */
#define IN_PORT_6_NAME                 Ts
#define INPUT_6_DIMS_ND                {1,1}
#define INPUT_6_NUM_ELEMS              1
#define INPUT_6_WIDTH                  1
#define INPUT_DIMS_6_COL               1
#define INPUT_6_DTYPE                  real_T
#define INPUT_6_COMPLEX                COMPLEX_NO
#define INPUT_6_UNIT                   ""
#define IN_6_BUS_BASED                 0
#define IN_6_BUS_NAME
#define IN_6_DIMS                      1-D
#define INPUT_6_FEEDTHROUGH            1
#define IN_6_ISSIGNED                  0
#define IN_6_WORDLENGTH                8
#define IN_6_FIXPOINTSCALING           1
#define IN_6_FRACTIONLENGTH            9
#define IN_6_BIAS                      0
#define IN_6_SLOPE                     0.125

/* Input Port  7 */
#define IN_PORT_7_NAME                 Ia_medido
#define INPUT_7_DIMS_ND                {1,1}
#define INPUT_7_NUM_ELEMS              1
#define INPUT_7_WIDTH                  1
#define INPUT_DIMS_7_COL               1
#define INPUT_7_DTYPE                  real_T
#define INPUT_7_COMPLEX                COMPLEX_NO
#define INPUT_7_UNIT                   ""
#define IN_7_BUS_BASED                 0
#define IN_7_BUS_NAME
#define IN_7_DIMS                      1-D
#define INPUT_7_FEEDTHROUGH            1
#define IN_7_ISSIGNED                  0
#define IN_7_WORDLENGTH                8
#define IN_7_FIXPOINTSCALING           1
#define IN_7_FRACTIONLENGTH            9
#define IN_7_BIAS                      0
#define IN_7_SLOPE                     0.125

/* Input Port  8 */
#define IN_PORT_8_NAME                 Ib_medido
#define INPUT_8_DIMS_ND                {1,1}
#define INPUT_8_NUM_ELEMS              1
#define INPUT_8_WIDTH                  1
#define INPUT_DIMS_8_COL               1
#define INPUT_8_DTYPE                  real_T
#define INPUT_8_COMPLEX                COMPLEX_NO
#define INPUT_8_UNIT                   ""
#define IN_8_BUS_BASED                 0
#define IN_8_BUS_NAME
#define IN_8_DIMS                      1-D
#define INPUT_8_FEEDTHROUGH            1
#define IN_8_ISSIGNED                  0
#define IN_8_WORDLENGTH                8
#define IN_8_FIXPOINTSCALING           1
#define IN_8_FRACTIONLENGTH            9
#define IN_8_BIAS                      0
#define IN_8_SLOPE                     0.125

/* Input Port  9 */
#define IN_PORT_9_NAME                 Nr
#define INPUT_9_DIMS_ND                {1,1}
#define INPUT_9_NUM_ELEMS              1
#define INPUT_9_WIDTH                  1
#define INPUT_DIMS_9_COL               1
#define INPUT_9_DTYPE                  real_T
#define INPUT_9_COMPLEX                COMPLEX_NO
#define INPUT_9_UNIT                   ""
#define IN_9_BUS_BASED                 0
#define IN_9_BUS_NAME
#define IN_9_DIMS                      1-D
#define INPUT_9_FEEDTHROUGH            1
#define IN_9_ISSIGNED                  0
#define IN_9_WORDLENGTH                8
#define IN_9_FIXPOINTSCALING           1
#define IN_9_FRACTIONLENGTH            9
#define IN_9_BIAS                      0
#define IN_9_SLOPE                     0.125
#define NUM_OUTPUTS                    2

/* Output Port  0 */
#define OUT_PORT_0_NAME                x_pred_out
#define OUTPUT_0_DIMS_ND               {5,1}
#define OUTPUT_0_NUM_ELEMS             5
#define OUTPUT_0_WIDTH                 5
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     2-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                x_corr_out
#define OUTPUT_1_DIMS_ND               {5,1}
#define OUTPUT_1_NUM_ELEMS             5
#define OUTPUT_1_WIDTH                 5
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 real_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUTPUT_1_UNIT                  ""
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     2-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           1
#define SOURCEFILES                    "__SFB__"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             0
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

extern void ekf_6steps_Start_wrapper(void);
extern void ekf_6steps_Outputs_wrapper(const real_T *Va,
  const real_T *Vb,
  const real_T *R,
  const real_T *L,
  const real_T *Kt,
  const real_T *J,
  const real_T *Ts,
  const real_T *Ia_medido,
  const real_T *Ib_medido,
  const real_T *Nr,
  real_T *x_pred_out,
  real_T *x_corr_out);

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(outputDimsInfo);
  ssSetNumSFcnParams(S, NPARAMS);
  if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_NUM_ELEMS);
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /* Input Port 1 */
  ssSetInputPortWidth(S, 1, INPUT_1_NUM_ELEMS);
  ssSetInputPortDataType(S, 1, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

  /* Input Port 2 */
  ssSetInputPortWidth(S, 2, INPUT_2_NUM_ELEMS);
  ssSetInputPortDataType(S, 2, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/

  /* Input Port 3 */
  ssSetInputPortWidth(S, 3, INPUT_3_NUM_ELEMS);
  ssSetInputPortDataType(S, 3, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 3, 1);/*direct input signal access*/

  /* Input Port 4 */
  ssSetInputPortWidth(S, 4, INPUT_4_NUM_ELEMS);
  ssSetInputPortDataType(S, 4, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 4, INPUT_4_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 4, 1);/*direct input signal access*/

  /* Input Port 5 */
  ssSetInputPortWidth(S, 5, INPUT_5_NUM_ELEMS);
  ssSetInputPortDataType(S, 5, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 5, INPUT_5_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 5, 1);/*direct input signal access*/

  /* Input Port 6 */
  ssSetInputPortWidth(S, 6, INPUT_6_NUM_ELEMS);
  ssSetInputPortDataType(S, 6, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 6, INPUT_6_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 6, INPUT_6_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 6, 1);/*direct input signal access*/

  /* Input Port 7 */
  ssSetInputPortWidth(S, 7, INPUT_7_NUM_ELEMS);
  ssSetInputPortDataType(S, 7, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 7, INPUT_7_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 7, INPUT_7_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 7, 1);/*direct input signal access*/

  /* Input Port 8 */
  ssSetInputPortWidth(S, 8, INPUT_8_NUM_ELEMS);
  ssSetInputPortDataType(S, 8, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 8, INPUT_8_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 8, INPUT_8_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 8, 1);/*direct input signal access*/

  /* Input Port 9 */
  ssSetInputPortWidth(S, 9, INPUT_9_NUM_ELEMS);
  ssSetInputPortDataType(S, 9, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 9, INPUT_9_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 9, INPUT_9_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 9, 1);/*direct input signal access*/

  /*
   * Configure the Units for Input Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId inUnitIdReg;
    ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 0, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Va of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_1_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 1, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Vb of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_2_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 2, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port R of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_3_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 3, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port L of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_4_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 4, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Kt of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_5_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 5, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port J of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_6_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 6, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Ts of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_7_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 7, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Ia_medido of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_8_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 8, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Ib_medido of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_9_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 9, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Nr of S-Function ekf_6steps");
      return;
    }

#endif

  }

  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssAllowSignalsWithMoreThan2D(S);
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_0_NUM_ELEMS;
  int_T out0Dims[] = OUTPUT_0_DIMS_ND;
  outputDimsInfo.dims = out0Dims;
  ssSetOutputPortDimensionInfo(S, 0, &outputDimsInfo);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_1_NUM_ELEMS;
  int_T out1Dims[] = OUTPUT_1_DIMS_ND;
  outputDimsInfo.dims = out1Dims;
  ssSetOutputPortDimensionInfo(S, 1, &outputDimsInfo);
  ssSetOutputPortDataType(S, 1, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /*
   * Configure the Units for Output Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId outUnitIdReg;
    ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 0, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port x_pred_out of S-Function ekf_6steps");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_1_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 1, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port x_corr_out of S-Function ekf_6steps");
      return;
    }

#endif

  }

  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "24.1");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_DEFAULT_PORT_DIMENSION_INFO

static void mdlSetDefaultPortDimensionInfo(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(portDimsInfo);
  int_T dims[2];

  /* Setting default dimensions for output port 0 */
  portDimsInfo.width = OUTPUT_0_NUM_ELEMS;
  dims[0] = OUTPUT_0_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 0) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 0, &portDimsInfo);
  }

  /* Setting default dimensions for output port 1 */
  portDimsInfo.width = OUTPUT_1_NUM_ELEMS;
  dims[0] = OUTPUT_1_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 1) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 1, &portDimsInfo);
  }

  return;
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
  ekf_6steps_Start_wrapper();
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const real_T *Va = (real_T *) ssGetInputPortRealSignal(S, 0);
  const real_T *Vb = (real_T *) ssGetInputPortRealSignal(S, 1);
  const real_T *R = (real_T *) ssGetInputPortRealSignal(S, 2);
  const real_T *L = (real_T *) ssGetInputPortRealSignal(S, 3);
  const real_T *Kt = (real_T *) ssGetInputPortRealSignal(S, 4);
  const real_T *J = (real_T *) ssGetInputPortRealSignal(S, 5);
  const real_T *Ts = (real_T *) ssGetInputPortRealSignal(S, 6);
  const real_T *Ia_medido = (real_T *) ssGetInputPortRealSignal(S, 7);
  const real_T *Ib_medido = (real_T *) ssGetInputPortRealSignal(S, 8);
  const real_T *Nr = (real_T *) ssGetInputPortRealSignal(S, 9);
  real_T *x_pred_out = (real_T *) ssGetOutputPortRealSignal(S, 0);
  real_T *x_corr_out = (real_T *) ssGetOutputPortRealSignal(S, 1);
  ekf_6steps_Outputs_wrapper(Va, Vb, R, L, Kt, J, Ts, Ia_medido, Ib_medido, Nr,
    x_pred_out, x_corr_out);
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
