modelNames = ["M0","M1","M2"];
signalsIa = {Ia_planta_M0, Ia_planta_M1, Ia_planta_M2};
signalsIb = {Ib_planta_M0, Ib_planta_M1, Ib_planta_M2};
signalsWe = {We_planta_M0, We_planta_M1, We_planta_M2};
signalsWm = {Wm_planta_M0, Wm_planta_M1, Wm_planta_M2};
signalsTe = {Te_planta_M0, Te_planta_M1, Te_planta_M2};

fe_ref = Wm_ref.data(1)*P/(2*pi);
Kmax = 5;
t_inicial = 0.2;
t_final = 0.8;
Fmax = 2000;
doPlot = true;

for k = 1:numel(modelNames)
    res(k).name = modelNames(k);

    res(k).Ia = fft_analyzer(signalsIa{k}, ...
        'Name',"Ia_"+modelNames(k), ...
        'MaxPeaks',20,'MinPeakFrac',0.05,...
        'Fref',fe_ref,'Fmax',Fmax,'Kmax',Kmax,...
        'TimeWindow',[t_inicial t_final],'DoPlot',doPlot);

    res(k).Ib = fft_analyzer(signalsIb{k}, ...
        'Name',"Ib_"+modelNames(k), ...
        'MaxPeaks',20,'MinPeakFrac',0.05,...
        'Fref',fe_ref,'Fmax',Fmax,'Kmax',Kmax,...
        'TimeWindow',[t_inicial t_final],'DoPlot',doPlot);

    res(k).We = fft_analyzer(signalsWe{k}, ...
        'Name',"We_"+modelNames(k), ...
        'MaxPeaks',20,'MinPeakFrac',0.05,...
        'Fref',fe_ref,'Fmax',Fmax,'Kmax',Kmax,...
        'TimeWindow',[t_inicial t_final],'DoPlot',doPlot);

    res(k).Wm = fft_analyzer(signalsWm{k}, ...
        'Name',"Wm_"+modelNames(k), ...
        'MaxPeaks',20,'MinPeakFrac',0.05,...
        'Fref',fe_ref,'Fmax',Fmax,'Kmax',Kmax,...
        'TimeWindow',[t_inicial t_final],'DoPlot',doPlot);

    res(k).Te = fft_analyzer(signalsTe{k}, ...
        'Name',"Te_"+modelNames(k), ...
        'MaxPeaks',20,'MinPeakFrac',0.05,...
        'Fref',fe_ref,'Fmax',Fmax,'Kmax',Kmax,...
        'TimeWindow',[t_inicial t_final],'DoPlot',doPlot);

    res(k).fe = res(k).We.mean/(2*pi);
end