modelNames = ["M2"];

signalsIa = {Ia_planta_M2};
signalsIb = {Ib_planta_M2};

signalsId = {Id_M2};
signalsIq = {Iq_M2};

signalsWe = {We_planta_M2};
signalsWm = {Wm_planta_M2};

signalsTe = {Te_planta_M2};


% =========================================================================
% FRECUENCIA ELÉCTRICA DE REFERENCIA
% =========================================================================

P = 50;

% Usar velocidad final de operación
Wm_operacion = Wm_ref.Data(end);

fe_ref = ...
    abs(Wm_operacion) * P / (2*pi);


% =========================================================================
% PARÁMETROS FFT
% =========================================================================

Kmax = 5;

t_inicial = 0.06;
t_final   = 0.45;

Fmax = 2000;

doPlot = true;


% =========================================================================
% ANÁLISIS
% =========================================================================

for k = 1:numel(modelNames)

    res(k).name = modelNames(k);


    % ---------------------------------------------------------------------
    % Ia
    % ---------------------------------------------------------------------

    res(k).Ia = fft_analyzer( ...
        signalsIa{k}, ...
        'Name',"Ia_"+modelNames(k), ...
        'MaxPeaks',20, ...
        'MinPeakFrac',0.05, ...
        'Fref',fe_ref, ...
        'Fmax',Fmax, ...
        'Kmax',Kmax, ...
        'TimeWindow',[t_inicial t_final], ...
        'DoPlot',doPlot);


    % ---------------------------------------------------------------------
    % Ib
    % ---------------------------------------------------------------------

    res(k).Ib = fft_analyzer( ...
        signalsIb{k}, ...
        'Name',"Ib_"+modelNames(k), ...
        'MaxPeaks',20, ...
        'MinPeakFrac',0.05, ...
        'Fref',fe_ref, ...
        'Fmax',Fmax, ...
        'Kmax',Kmax, ...
        'TimeWindow',[t_inicial t_final], ...
        'DoPlot',doPlot);


    % ---------------------------------------------------------------------
    % Id
    % ---------------------------------------------------------------------

    res(k).Id = fft_analyzer( ...
        signalsId{k}, ...
        'Name',"Id_"+modelNames(k), ...
        'MaxPeaks',20, ...
        'MinPeakFrac',0.05, ...
        'Fref',fe_ref, ...
        'Fmax',Fmax, ...
        'Kmax',Kmax, ...
        'TimeWindow',[t_inicial t_final], ...
        'DoPlot',doPlot);


    % ---------------------------------------------------------------------
    % Iq
    % ---------------------------------------------------------------------

    res(k).Iq = fft_analyzer( ...
        signalsIq{k}, ...
        'Name',"Iq_"+modelNames(k), ...
        'MaxPeaks',20, ...
        'MinPeakFrac',0.05, ...
        'Fref',fe_ref, ...
        'Fmax',Fmax, ...
        'Kmax',Kmax, ...
        'TimeWindow',[t_inicial t_final], ...
        'DoPlot',doPlot);


    % ---------------------------------------------------------------------
    % Velocidad eléctrica
    % ---------------------------------------------------------------------

    res(k).We = fft_analyzer( ...
        signalsWe{k}, ...
        'Name',"We_"+modelNames(k), ...
        'MaxPeaks',20, ...
        'MinPeakFrac',0.05, ...
        'Fref',fe_ref, ...
        'Fmax',Fmax, ...
        'Kmax',Kmax, ...
        'TimeWindow',[t_inicial t_final], ...
        'DoPlot',doPlot);


    % ---------------------------------------------------------------------
    % Velocidad mecánica
    % ---------------------------------------------------------------------

    res(k).Wm = fft_analyzer( ...
        signalsWm{k}, ...
        'Name',"Wm_"+modelNames(k), ...
        'MaxPeaks',20, ...
        'MinPeakFrac',0.05, ...
        'Fref',fe_ref, ...
        'Fmax',Fmax, ...
        'Kmax',Kmax, ...
        'TimeWindow',[t_inicial t_final], ...
        'DoPlot',doPlot);


    % ---------------------------------------------------------------------
    % Torque electromagnético
    % ---------------------------------------------------------------------

    res(k).Te = fft_analyzer( ...
        signalsTe{k}, ...
        'Name',"Te_"+modelNames(k), ...
        'MaxPeaks',20, ...
        'MinPeakFrac',0.05, ...
        'Fref',fe_ref, ...
        'Fmax',Fmax, ...
        'Kmax',Kmax, ...
        'TimeWindow',[t_inicial t_final], ...
        'DoPlot',doPlot);


    % ---------------------------------------------------------------------
    % Frecuencia eléctrica media
    % ---------------------------------------------------------------------

    res(k).fe = ...
        abs(res(k).We.mean) / (2*pi);

end